// Code generated by Slice Machine. DO NOT EDIT.

import AboutMe from "./AboutMe/index.svelte";
import FeaturedBlogs from "./FeaturedBlogs/index.svelte";
import FeaturedProjects from "./FeaturedProjects/index.svelte";

export const components = {
  about_me: AboutMe,
  featured_blogs: FeaturedBlogs,
  featured_projects: FeaturedProjects,
};
