// Code generated by Slice Machine. DO NOT EDIT.

import FeaturedBlogs from "./FeaturedBlogs/index.svelte";
import FeaturedProjects from "./FeaturedProjects/index.svelte";

export const components = {
  featured_blogs: FeaturedBlogs,
  featured_projects: FeaturedProjects,
};
